---
- include_role:
    name: pureport.network.google_cloud_interconnect
    tasks_from: present.yaml
  vars:
    gcp_region: "{{ region }}"
    gcp_network_name: "vpc-{{ network_id[0:6] }}"
    gcp_router_name: "router-{{ connection_id[0:6] }}"
    gcp_interconnect_name: "vlan-{{ connection_id[0:6] }}"
    pureport_network_name: "network-{{ network_id[0:6] }}"
    pureport_connection_name: "conn-{{ connection_id[0:6] }}"
    pureport_connection_speed: "{{ speed }}"

- set_fact:
    connection_state:
      gcp_network: "{{ gcp_network }}"
      gcp_routers: "{{ gcp_routers }}"
      gcp_attachments: "{{ gcp_attachments }}"
      pureport_network: "{{ pureport_network }}"
      pureport_connection: "{{ pureport_connection }}"
