---
- fail:
    msg: "state value must be one of `present`, `absent`, got `{{ state }}`"
  when:
    - state is defined
    - state.lower() not in ['present', 'absent']

- include_tasks: { file: "{{ state | default('present') }}.yaml" }

