---
- set_fact:
    fabric_id: "{{ fabric_name | default('default') | hash('sha1') }}"
    connection_id: "{{ connection_name | default(omit) | hash('sha1') }}"

- name: create pureport_connection_region_map fact
  set_fact:
    pureport_connection_region_map:
      us-west1: "/locations/us-sea"
      us-west2: "/locations/us-sjc"
      us-east1: "/locations/us-wdc"
      us-east4: "/locations/us-wdc"
      us-central1: "/locations/us-chi"

- assert:
    that:
      - connection_region is defined
      - connection_region in pureport_connection_region_map.keys()
    fail_msg: "missing or invalid google cloud region"
    quiet: yes

- assert:
    that:
      - connection_speed is defined
      - connection_speed | int in [50, 100, 200, 300, 400, 500, 1000, 5000, 10000]
    fail_msg: "missing or invalid value for `connection_speed`"
    quiet: yes

- name: get the current resource
  google.cloud.gcp_compute_network_info:
    project: "{{ lookup('env', 'GCP_PROJECT') }}"
    filters:
      - "name = {{ network_name }}"
  register: network

- fail:
    msg: "`{{ network_name }}` does not exist"
  when: network.resources == []

- name: create google cloud router
  google.cloud.gcp_compute_router:
    name: "router-{{ connection_id[0:6] }}-{{ item }}"
    project: "{{ lookup('env', 'GCP_PROJECT') }}"
    region: "{{ connection_region }}"
    network: { selfLink: "{{ network.resources.0.selfLink }}" }
    bgp: { asn: 16550 }
  with_sequence: start=1 count=2
  register: gcp_routers

- name: create google cloud interconnect attachments
  google.cloud.gcp_compute_interconnect_attachment:
    name: "vlan-{{ connection_id[0:6] }}-{{ index + 1 }}"
    project: "{{ lookup('env', 'GCP_PROJECT') }}"
    region: "{{ connection_region }}"
    router: { selfLink: "{{ item.selfLink }}" }
    type: PARTNER
    admin_enabled: true
    edge_availability_domain: "AVAILABILITY_DOMAIN_{{ index + 1 }}"
  loop: "{{ gcp_routers.results }}"
  loop_control:
    index_var: index
  register: gcp_attachments

- name: create pureport network
  pureport.fabric.network:
    name: "network-{{ fabric_id[0:6] }}"
    description: "{{ pureport_network_description | default(omit) }}"
    account_href: "/accounts/{{ lookup('env', 'PUREPORT_ACCOUNT_ID') }}"
  register: pureport_network

- name: create connection from google cloud to pureport
  pureport.fabric.google_cloud_interconnect_connection:
    name: "conn-{{ connection_id[0:6] }}"
    network_href: "{{ pureport_network.href }}"
    location_href: "{{ pureport_connection_region_map[connection_region] }}"
    speed: "{{ connection_speed }}"
    high_availability: true
    billing_term: HOURLY
    primary_pairing_key: "{{ gcp_attachments.results.0.pairingKey }}"
    secondary_pairing_key: "{{ gcp_attachments.results.1.pairingKey }}"
    wait_for_server: "{{ pureport_connection_wait_for_server | default(omit) }}"
  register: pureport_connection

- import_role:
    name: pureport.network.file
    tasks_from: put
  vars:
    key: "/connections/pureport/{{ connection_id }}"
    value:
      gcp_routers: "{{ gcp_routers }}"
      gcp_attachments: "{{ gcp_attachments }}"
      pureport_network: "{{ pureport_network }}"
      pureport_connection: "{{ pureport_connection }}"
