---
- fail:
    msg: "missing required value for connection_name"
  when: connection_name is undefined

- pureport.fabric.connections_info:
    account_href: "/accounts/{{ lookup('env', 'PUREPORT_ACCOUNT_ID') }}"
  register: pureport_connections

- set_fact:
    pureport_connection: "{{ pureport_connections.connections |
                            selectattr('name', 'eq', connection_name) |
                            list |
                            first }}"

- set_fact:
    key: "/connections/pureport/{{ pureport_connection.id }}"

- include_role:
    name: pureport.network.file
    tasks_from: get

- block:
    - name: get the current vpc virtual gateway (if configured)
      community.aws.ec2_vpc_vgw_info:
        region: "{{ aws_region }}"
        vpn_gateway_ids: "{{ aws_vgw_id }}"
      register: this

    - set_fact:
        vgw_tag: "{{ this.virtual_gateways.0.tags |
                     selectattr('key', 'eq', 'Name') |
                     list |
                     first }}"

    - name: remove the aws vpc virtual gateway
      community.aws.ec2_vpc_vgw:
        name: "{{ vgw_tag.value }}"
        region: "{{ aws_region }}"
        state: absent
      register: aws_vgw_result
      delay: 30
      until: aws_vgw_result is not failed
      retries: 10
  when: aws_vgw_id != omit

- name: remove the aws direct connect virtual interfaces
  community.aws.aws_direct_connect_virtual_interface:
    connection_id: "{{ item.connection_id }}"
    virtual_interface_id: "{{ item.virtual_interface_id }}"
    region: "{{ item.region }}"
    state: absent
  loop: "{{ aws_virtual_interfaces.results }}"

- name: remove the aws direct connect connection
  community.aws.aws_direct_connect_connection:
    connection_id: "{{ item.connection_id }}"
    region: "{{ item.region }}"
    state: absent
  register: aws_dcg_result
  delay: 30
  until: aws_dcg_result is not failed
  retries: 30
  loop: "{{ aws_virtual_interfaces.results }}"

- name: remove the aws direct connect gateway
  community.aws.aws_direct_connect_gateway:
    direct_connect_gateway_id: "{{ aws_direct_connect_gateway.direct_connect_gateway_id }}"
    region: "{{ aws_region }}"
    state: absent

- name: remove the aws connection to pureport
  pureport.fabric.aws_direct_connect_connection:
    name: "{{ pureport_connection.name }}"
    network_href: "{{ pureport_connection.network.href }}"
    location_href: "{{ pureport_connection.location.href }}"
    speed: "{{ pureport_connection.speed }}"
    aws_account_id: "{{ pureport_connection.aws_account_id }}"
    aws_region: "{{ pureport_connection.aws_region }}"
    wait_for_server: true
    state: absent

- name: get all connections for pureport network
  pureport.fabric.connections_info:
    network_href: "{{ pureport_connection.network.href }}"
  register: pureport_connections

- name: remove pureport network (if no connections remain)
  pureport.fabric.network:
    name: "{{ pureport_connection.network.title }}"
    account_href: "/accounts/{{ lookup('env', 'PUREPORT_ACCOUNT_ID') }}"
    state: absent
  when: pureport_connections.connections == []

- include_role:
    name: pureport.network.file
    tasks_from: delete
