---
- set_fact:
    id: "{{ fabric | default('default') | hash('sha1') }}"

- set_fact:
    pureport_location_map:
      chicago: ["/locations/us-chi", "Chicago", "northcentralus"]
      dallas: ["/locations/us-dal", "Dallas", "southcentralus"]
      seattle: ["/locations/us-sea", "Seattle", "westus2"]
      silicon_valley: ["/locations/us-sjc", "Silicon Valley", "westus"]
      washington_dc: ["/locations/us-wdc", "Washington DC", "eastus"]

- name: create the azure resource group
  azure.azcollection.azure_rm_resourcegroup:
    name: "resource-group-{{ id[0:6] }}"
    location: "{{ pureport_location_map[azure_location.replace(' ', '_').lower()].2 }}"
  register: azure_resource_group
  when:
    - azure_resource_group is undefined
    - azure_resource_group_name is undefined

- set_fact:
    azure_resource_group_name: "{{ azure_resource_group.state.name }}"
  when:
    - azure_resource_group is defined
    - azure_resource_group_name is undefined

- set_fact:
    azure_api_version: "2018-11-01"
    azure_api_prefix: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ azure_resource_group_name }}/providers/Microsoft.Network"
    azure_circuit_name: "circuit-{{ id[0:6] }}"

# https://docs.microsoft.com/en-us/rest/api/expressroute/expressroutecircuits/createorupdate
- name: create the azure express route circuit
  azure.azcollection.azure_rm_resource:
    url: "{{ azure_api_prefix }}/expressRouteCircuits/{{ azure_circuit_name }}"
    api_version: "{{ azure_api_version }}"
    idempotency: true
    body:
      location: "{{ azure_resource_group.state.location }}"
      sku:
        name: Standard_MeteredData
        tier: Standard
        family: MeteredData
      properties:
        serviceProviderProperties:
          serviceProviderName: Equinix
          peeringLocation: "{{ pureport_location_map[azure_location.replace(' ', '_').lower()].1 }}"
          bandwidthInMbps: "{{ pureport_connection_speed }}"
  register: azure_express_route_circuit

- name: wait until the azure express route circuit has been provisioned
  azure.azcollection.azure_rm_resource:
    url: "{{ azure_api_prefix }}/expressRouteCircuits/{{ azure_circuit_name }}"
    api_version: "{{ azure_api_version }}"
    method: GET
  register: azure_express_route
  until: azure_express_route.response.properties.serviceKey != '00000000-0000-0000-0000-000000000000'
  retries: 30
  delay: 10

- name: create the pureport network
  pureport.fabric.network:
    name: "network-{{ id[0:6] }}"
    description: "{{ pureport_network_description | default(omit) }}"
    account_href: "/accounts/{{ lookup('env', 'PUREPORT_ACCOUNT_ID') }}"
  register: pureport_network

- set_fact:
    connection_id: "{{ azure_circuit_name | hash('sha1') }}"

- name: create the azure connection to the pureport network
  pureport.fabric.azure_express_route_connection:
    name: "conn-{{ connection_id[0:6] }}"
    network_href: "{{ pureport_network.href }}"
    location_href: "{{ pureport_location_map[azure_location.replace(' ', '_').lower()].0 }}"
    speed: "{{ pureport_connection_speed }}"
    high_availability: true
    billing_term: HOURLY
    service_key: "{{ azure_express_route.response.properties.serviceKey }}"
    wait_for_server: true
  register: pureport_connection

# https://docs.microsoft.com/en-us/rest/api/expressroute/expressroutecircuitpeerings/createorupdate
- name: update the azure express route circuit peering configuration
  azure.azcollection.azure_rm_resource:
    url: "{{ azure_api_prefix }}/expressRouteCircuits/{{ azure_circuit_name }}/peerings/AzurePrivatePeering"
    api_version: "{{ azure_api_version }}"
    idempotency: true
    body:
      properties:
        peeringType: AzurePrivatePeering
        peerASN: "{{ pureport_connection.primary_gateway.bgp_config.pureport_asn }}"
        primaryPeerAddressPrefix: "{{ pureport_connection.primary_gateway.bgp_config.peering_subnet }}"
        secondaryPeerAddressPrefix: "{{ pureport_connection.secondary_gateway.bgp_config.peering_subnet }}"
        vlanId: "{{ pureport_connection.primary_gateway.vlan }}"
        sharedKey: "{{ pureport_connection.primary_gateway.bgp_config.password }}"
  register: azure_express_route_peering
